### ISSUE TITLE
Update to Support NumPy 2.0 and PyCharm 3.10 Compatibility

### ISSUE THREAD

**Issue by itszoetom** [sjara/jaratoolbox#18]
This issue addresses updates required in various jaratoolbox scripts to support compatibility with my versions of NumPy (2.0) and  PyCharm (3.10):

**celldatabase.py**

- Line 733: Change np.object to object to resolve deprecation warnings in NumPy 2.0.

- Line 536: Change .append to ._append for proper functionality with the updated NumPy version.

**extrafuncs.py**

- Line 12: Change np.NaN to np.nan to ensure correct usage of NumPy.

**feat004_inforec.py**

- Line 10: Update recordingTrack='DiD' to recordingTrack='anteromedialDiD' for consistency in naming conventions.

**histologyanalysis.py**

- Line 800: Change the format string from f'registration_{brainArea}' to f'registration{brainArea}' to correct the output.

**Comment by sjara** [comment]
Thank you for sending these. Below is the commit that addresses each point. Please pull the latest version of jaratoolbox and let me know if anything still fails.

**celldatabase.py**
- Line 733: Change np.object to object to resolve deprecation warnings in NumPy 2.0.
https://github.com/sjara/jaratoolbox/commit/c9d450855d188a917a3e55876501f598ac6db4f1

- Line 536: Change .append to ._append for proper functionality with the updated NumPy version.
https://github.com/sjara/jaratoolbox/commit/39424b04d677afee6a3fd0ac23326857c69971ad

**extrafuncs.py**
- Line 12: Change np.NaN to np.nan to ensure correct usage of NumPy.
https://github.com/sjara/jaratoolbox/commit/5572dcb7fa72ae81e96383c1839e7ce85e7bebde

**feat004_inforec.py (Note that this is a bug in a different repository)**
- Line 10: Update recordingTrack='DiD' to recordingTrack='anteromedialDiD' for consistency in naming conventions.
https://github.com/sjara/jarainfo/commit/35d00e604e37919dbd559fd13d32d22ee8b60cd1

**histologyanalysis.py**
- Line 800: Change the format string from f'registration_{brainArea}' to f'registration{brainArea}' to correct the output.
**Not changed.** We have decided to use the original format f'registration_{brainArea}'. Please rename your registration and recordingTracks folders so they have the additional underscore (this may require also changing the SVG files to point to the correct files), or copy the data again from the server (which we have updated to the format with underscores).
